export const MOVIE_INFOS = {
    Type: 'Tipo',
    Year: 'Año',
    Released: 'Estreno',
    imdbRating: 'IMDB Rating',
    Metascore: 'Metascore Rating',
    Genre: 'Género',
    Language: 'Idioma',
    Country: 'País',
    Runtime: 'Runtime',
    Rated: 'Puntuacion',
    Director: 'Director',
    Actors: 'Actores',
    Writer: 'Escritor',
    Production: 'Producción',
}
